version: '3.7'

services:
  main-app:
    build: .
    ports:
      - "80:8080"
    environment:
      - POSTGRES_CONNECT_STRING=host=db port=5432 user=postgres password=postgres dbname=riocabal connect_timeout=10
      - POSTGRES_POOL_SIZE=4
      - JWK_STRING=b3d3038c4f8c44589de316439d3d227c
    restart: on-failure
    networks:
      - intranet
    depends_on:
      - db
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=riocabal
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data/pgdata
        read_only: false

    networks:
      - intranet

volumes:
  pgdata:

networks:
  intranet:
